server:
  port: 8081

spring:
  application:
    name: "customers"

  datasource:
    url: jdbc:postgresql://localhost:5432/customersdb
    username: ${CUSTOMERS_DB_USERNAME}
    password: ${CUSTOMERS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    function:
      definition: updateUserId
    stream:
      bindings:
        updateUserId-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        customerCreated-out-0:
          destination: send-communication
    vault:
      default-context: customers-db

accounts:
  message: "Welcome to bunthoeurn customers related docker APIs"