server:
  port: 8083

spring:
  application:
    name: "events"

  # datasource:
  #   url: jdbc:postgresql://localhost:5440/eventsdb
  #   username: ${EVENTS_DB_USERNAME:eventsdb}
  #   password: ${EVENTS_DB_PASSWORD:eventsdb}
  #   driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    function:
      # Specific to the events/audit logic
      definition: auditSink
    stream:
      bindings:
        auditSink-in-0:
          destination: banking.audit.logs
          group: audit-service-group
    vault:
      # Inherits URI and Token from global application.yml
      default-context: events-db

events:
  message: "Welcome to bunthoeurn events related docker APIs"
