server:
  port: 8090

spring:
  application:
    name: gatewayserver

  # Reactive Database Configuration
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5439/gatewaydb
    username: ${GATEWAY_DB_USERNAME}
    password: ${GATEWAY_DB_PASSWORD}

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          # Pointing to your Keycloak instance
          jwk-set-uri: "http://localhost:7080/realms/banking-platform/protocol/openid-connect/certs"

  cloud:
    # Inherits Vault URI and Token from global application.yml
    vault:
      default-context: gateway-db

# management, health, and metrics are now inherited from global!