server:
  port: 8090
spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071"
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5439/gatewaydb
    username: gatewaydb
    password: gatewaydb
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/banking-platform/protocol/openid-connect/certs"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com:
      example:
        springgateway: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"