server:
  port: 8082
spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:5438/usersdb
    username: usersdb
    password: usersdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    function:
      definition: createUser
    stream:
      bindings:
        createUser-in-0:
          destination: send-communication
          group: ${spring.application.name}
        createUser-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: elastic123

logging:
  level:
    com:
      example:
        users_service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

keycloak:
  admin:
    base-url: http://localhost:7080
    realm: banking-platform
    client-id: users-service
    client-secret: wjTMoFNvMJX6mbMzmUIEKEbEsscuTYUD
    username: api-user-service
    password: admin